### ISSUE TITLE
Problema al generar la factura

### ISSUE THREAD

**Issue by benshy7** [Vauxoo/odoo-venezuela#45]
l10n_ve_sale_purchase/model/stock.py

AttributeError: 'list' object has no attribute 'Key'

if context is None:
            context = {}
        data = super(StockPicking, self).action_invoice_create(
            cursor, user, ids, journal_id, group, type, context)
***    picking_id = data.keys()[0]     *** En este punto sucede el error
        invoice_id = data[picking_id]

No me deja generar la Factura en ventas.
Quisiera saber si me falta instalar alguna librería para la localización venezolana

**Comment by nhomar** [comment]
Version ?
Si compartes el traceback completo ayuda más.

**Comment by benshy7** [comment]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/server/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/server/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server/addons/stock_account/wizard/stock_invoice_onshipping.py", line 105, in open_invoice
    invoice_ids = self.create_invoice(cr, uid, ids, context=context)
  File "/opt/odoo/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server/addons/stock_account/wizard/stock_invoice_onshipping.py", line 148, in create_invoice
    context=context)
  File "/opt/odoo/server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server/addons/l10n_ve_sale_purchase/model/stock.py", line 47, in action_invoice_create
    picking_id = data.key()[0]
AttributeError: 'list' object has no attribute 'key'


Versión de Odoo V8, bajo servidor Ubuntu 14
